apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLables:
      name: flask-app
  template:
    metadata:
      lables:
        name: flask-app
    specs:
      containers:
        - name: flask-app
          image: manishthakur2/devops-eks-pipeline:latest
          ports:
            - containerPort: 5000
          livenessProbe:
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
